# Configure Rolls
rollFormula = "2d6"
rollShifting = true

# Define roll result ranges.
[rollResults]
[rollResults.crit]
range = "12+"
label = "Critical Success!"
[rollResults.success]
range = "10-11"
label = "Success!"
[rollResults.partial]
range = "7-9"
label = "Partial success"
[rollResults.failure]
range = "6-"
label = "Miss..."

########################################
## CHARACTERS ##########################
########################################
# Define the character group.
[character]

# Define stats.
[character.stats]
vitality = "Vitality"
composure = "Composure"
reason = "Reason"
presence = "Presence"
sensitivity = "Sensitivity"

# Define attributes.
[character.attributesTop]

#[character.attributesTop.style]
#type = "LongText"
#label = "Style"
#description = "Pick one, or make up your own"
#[character.attributesTop.takesYouBack]
#type = "LongText"
#label = "Takes You Back"
#description = "Pick three, or make up your own"



[character.attributesTop.conditions]
type = "TextMany"
label = "Conditions"
description = "When a Condition applies, take disadvantage"
lines = 5




[character.attributesTop.keyofthechild]
type = "ListMany"
label = "The Key of the Child"
description = "When you turn this Key, mark and narrate any of the below flashbacks that you wish."

[character.attributesTop.keyofthechild.options.routine]
label = "Home routine"
tooltip = "A flashback showing your latchkey kid routine whenever you got home from school."
[character.attributesTop.keyofthechild.options.outsider]
label = "Outsider"
tooltip = "A flashback showing how you were an outsider among your school peers."
[character.attributesTop.keyofthechild.options.parents]
label = "Imperfect parents"
tooltip = "A flashback to the moment when you realized your parents were imperfect."
[character.attributesTop.keyofthechild.options.happy]
label = "Genuine happiness"
tooltip = "A flashback to when you felt genuine happiness as a child."
[character.attributesTop.keyofthechild.options.trauma]
label = "Trauma"
tooltip = "A flashback to when you experienced childhood trauma."
[character.attributesTop.keyofthechild.options.growingup]
label = "Growing up"
tooltip = "A flashback to the moment when you realized childhood wasn't forever."
[character.attributesTop.keyofthechild.options.tvodyssey]
label = "TV Odyssey"
tooltip = "A flashback to when you first discovered TV Odyssey."

[character.attributesTop.keyofdesolation]
type = "ListMany"
label = "The Key of Desolation"
description = "When you turn this key, mark the first empty box."

[character.attributesTop.keyofdesolation.options.arch]
label = "THE SANDSTONE ARCH"
tooltip = "Unlock the Dawn question: 'Did you receive a Signal from the Other Side?'"
[character.attributesTop.keyofdesolation.options.well]
label = "THE FATHOMLESS WELL"
tooltip = "Your Reason modifier is reduced by 1 and your Sensitivity modifier is increased by 1 (max 3)."
[character.attributesTop.keyofdesolation.options.monolith]
label = "THE WANDERING MONOLITH"
tooltip = "Gain the Consult The Big Man Move."
[character.attributesTop.keyofdesolation.options.desert]
label = "THE CHROMATIC DESERT"
tooltip = """
    You can no longer be perceived by other characters and all memory of you is erased—it’s like you never existed.
    You can continue to conduct investigations, but the Clues you find are only available if you narrate them into an
    Odyssey tape scene."""
[character.attributesTop.keyofdesolation.options.signal]
label = "THE PURE-WHITE SIGNAL"
tooltip = "You lose contact with this world altogether. Tell the Keeper to play a white Odyssey tape and then retire this character."


# Define sidebar details.
[character.attributesLeft]


[character.attributesLeft.dawnquestions]
    type = "ListMany"
    label = "Dawn questions"
    description = "The first is always marked. The second is always marked after it is unlocked. At the beginning of a session, mark two more (four total marked)."
    [character.attributesLeft.dawnquestions.options.mystery]
        label = "Mystery solved"
        tooltip = "Did the Latchkeys resolve a mystery?"
    [character.attributesLeft.dawnquestions.options.signal]
        label = "Signal from the Other Side"
        tooltip = "Did you receive a Signal from the Other Side? (locked until you mark THE SANDSTONE ARCH)"
    [character.attributesLeft.dawnquestions.options.memory]
        label = "Good memory"
        tooltip = "Did you share a good memory from your childhood?"
    [character.attributesLeft.dawnquestions.options.vulnerable]
        label = "Be vulnerable"
        tooltip = "Were you vulnerable with someone?"
    [character.attributesLeft.dawnquestions.options.deeplake]
        label = "Deep Lake reconnection"
        tooltip = "Did you go out of your way to reconnect with Deep Lake?"
    [character.attributesLeft.dawnquestions.options.monologue]
        label = "Chilling monologue"
        tooltip = "Did you deliver a chilling monologue about something that happened to you in the past?"
    [character.attributesLeft.dawnquestions.options.cutloose]
        label = "Cut loose"
        tooltip = "Did you cut loose for once?"

[character.attributesLeft.xp]
type = "Xp"
label = "XP Track"
description = "When you answer a Dawn question 'yes', or when a move says to, mark XP."
max = 6
default = 0


[character.attributesLeft.advances]
type = "ListMany"
label = "Advances"
description = "When you Advance, pick any one."
options = [
    "Increase an ability by 1 (max 3).|2",
    "Choose an additional Latchkey muove.|2",
    "Write a custom Latchkey move for your character.",
    "Unmark all the items in Your Corner of the House."
]


# Define groups for moves.
[character.moveTypes]
basic = "Basic Moves"
class = "Latchkey Moves"
other = "Other Moves"

# Define groups for equipment.
[character.equipmentTypes]
housecorner = "Your corner of the house"


########################################
## NPCS ################################
########################################
# Define stats.
[npc]
[npc.attributesTop]
[npc.attributesTop.decription]
type = "LongText"
label = "Description"
[npc.attributesTop.quote]
type = "LongText"
label = "Quote"

# Define logical groups for moves.
[npc.moveTypes]
custom = "Moves"

[npc.equipmentTypes]
loot = "Loot"
